pipeline {
    agent any

    tools {
        maven 'mymaven'   // or 'Maven' if that’s the exact name in Global Tool Config
    }

    stages {
        stage('build') {
            steps {
                sh 'mvn clean package'
            }
            post {
                success {
                    archiveArtifacts artifacts: '**/target/*.jar'
                }
            }
        }
    }
}
